name: Deploy Meilisearch to Render

on:
  workflow_dispatch:

jobs:
  deploy-meili:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create meili_data directory
        run: mkdir -p meili_data

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Meilisearch Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/meilisearch:latest \
            -f docker/meili.Dockerfile .

      - name: Push Meilisearch Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/meilisearch:latest

      - name: Trigger Render redeploy
        run: |
          curl --request POST \
            --url https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys \
            --header 'accept: application/json' \
            --header 'authorization: Bearer ${{ secrets.RENDER_API_KEY }}' \
            --header 'content-type: application/json' \
            --data '{
              "clearCache": "do_not_clear",
              "imageUrl": "docker.io/${{ secrets.DOCKER_USERNAME }}/meilisearch:latest"
            }'
